name: Deploy to server

on:
  push:
    branches:
      - horlakz/dev

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker images
        run: |
          docker build ./.docker/prod/ -t businessvtu:${{ github.sha }}

  run:
    runs-on: self-hosted

    needs:
      - build

    steps:
      - name: remove running container
        run: |
          docker rm --force businessvtu

      - name: Run Docker images
        run: |
          docker run -d -p 1000:3000 --name businessvtu businessvtu:${{ github.sha }}
